
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.geom.RoundRectangle2D;
import java.util.Random;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Office
 */
public class password_generator extends javax.swing.JFrame {

    /**
     * Creates new form password_generator
     */
    public password_generator() {
        setUndecorated(true);
        
        initComponents();
        cc.setVisible(false);
        setOpacity(0.8f);
        setLocationRelativeTo(null);

        setSize(400,300);
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0,0, getWidth(),getHeight(), 20,20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slider = new javax.swing.JSlider();
        n = new javax.swing.JCheckBox();
        sl = new javax.swing.JCheckBox();
        cl = new javax.swing.JCheckBox();
        sc = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pass = new javax.swing.JTextArea();
        sliderf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(400, 300));
        setMaximumSize(new java.awt.Dimension(535, 376));
        setMinimumSize(new java.awt.Dimension(535, 376));
        setResizable(false);
        getContentPane().setLayout(null);

        slider.setMaximum(20);
        slider.setValue(6);
        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        slider.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                sliderCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        slider.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sliderPropertyChange(evt);
            }
        });
        getContentPane().add(slider);
        slider.setBounds(32, 90, 392, 20);

        n.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        n.setText("Numbers");
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });
        getContentPane().add(n);
        n.setBounds(30, 110, 120, 30);

        sl.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        sl.setText("Small Letters");
        sl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slActionPerformed(evt);
            }
        });
        getContentPane().add(sl);
        sl.setBounds(30, 140, 160, 37);

        cl.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        cl.setText("Capital Letters");
        cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clActionPerformed(evt);
            }
        });
        getContentPane().add(cl);
        cl.setBounds(30, 170, 180, 37);

        sc.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        sc.setText("Special Characters");
        sc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scActionPerformed(evt);
            }
        });
        getContentPane().add(sc);
        sc.setBounds(30, 210, 210, 30);

        jButton1.setBackground(new java.awt.Color(51, 0, 255));
        jButton1.setFont(new java.awt.Font("Palace Script MT", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("Generate");
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 243, 432, 40);

        pass.setColumns(1);
        pass.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 24)); // NOI18N
        pass.setRows(5);
        pass.setText("deede");
        pass.setToolTipText("Click to Copy");
        pass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 0, 0), java.awt.Color.black, java.awt.Color.black));
        pass.setFocusable(false);
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pass);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 290, 432, 50);

        sliderf.setEditable(false);
        sliderf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sliderf.setText("6");
        sliderf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.pink, java.awt.Color.black));
        sliderf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sliderfActionPerformed(evt);
            }
        });
        getContentPane().add(sliderf);
        sliderf.setBounds(380, 60, 30, 30);

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel1.setText("Length");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 60, 100, 30);

        cc.setBackground(new java.awt.Color(0, 255, 0));
        cc.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        cc.setText("CODE COPIED!!");
        cc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cc.setOpaque(true);
        getContentPane().add(cc);
        cc.setBounds(150, 350, 200, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    private void clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String capitalLetters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String smallLetters = "abcdefghijklmnopqrstuvwxyz";
        String numbers = "0123456789";
        String specialCharacters = "!@#$%^&*";
        int length=slider.getValue();
        
        
         StringBuilder charSet = new StringBuilder();
        if (n.isSelected()) charSet.append(numbers);
        if (sl.isSelected()) charSet.append(smallLetters);
        if (cl.isSelected()) charSet.append(capitalLetters);
        if (sc.isSelected()) charSet.append(specialCharacters);
        
        StringBuilder passwordBuilder = new StringBuilder();
        Random random = new Random();
        
         for (int i = 0; i < length; i++) {
            int randomIndex = random.nextInt(charSet.length());
            passwordBuilder.append(charSet.charAt(randomIndex));
        }
         
            String s=passwordBuilder.toString();
        pass.setText(s);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sliderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sliderPropertyChange

// TODO add your handling code here:
    }//GEN-LAST:event_sliderPropertyChange

    private void sliderCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_sliderCaretPositionChanged
         // TODO add your handling code here:
    }//GEN-LAST:event_sliderCaretPositionChanged

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
    int a=slider.getValue();
    String b=Integer.toString(a);
    sliderf.setText(b);        // TODO add your handling code here:
    }//GEN-LAST:event_sliderStateChanged

    private void sliderfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sliderfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sliderfActionPerformed

    private void passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseClicked
            
        
        String selectedText = pass.getText();
                        if (selectedText != null && !selectedText.isEmpty()) {
                            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
                            StringSelection selection = new StringSelection(selectedText);
                            clipboard.setContents(selection, null);
                            System.out.println("Text copied to clipboard: " + selectedText);
                        } // TODO add your handling code here:
    }//GEN-LAST:event_passMouseClicked

    private void slActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slActionPerformed

    private void scActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(password_generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(password_generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(password_generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(password_generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new password_generator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cc;
    private javax.swing.JCheckBox cl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox n;
    private javax.swing.JTextArea pass;
    private javax.swing.JCheckBox sc;
    private javax.swing.JCheckBox sl;
    private javax.swing.JSlider slider;
    private javax.swing.JTextField sliderf;
    // End of variables declaration//GEN-END:variables

    private Shape RoundRectangle2D(int i, int i0, int width, int height, int i1, int i2) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
